### PR TITLE
add avrdude

### PR DESCRIPTION
**Pull request by LuckyTurtleDev**
for firmware updates

### CODE REVIEW

**Comment by yadomi** [comment]
Hello, I'm a bit late but what is the use case for avrdude ?

**Comment by Rindula** [comment]
avrdude seems to be used by repetier-server for the Firmwareupload to the printer. I found an issue [here](https://forum.repetier.com/discussion/5783/firmware-upload-nicht-mehr-moeglich), you might need to translate it, because it's german.

**Comment by Rindula** [comment]
_This mergerequest can be closed without merging, since avrdude is included in repetier-server by default by now._

**Comment by yadomi** [comment]
That's perfect, FYI `avrdude` is located in `/usr/local/Repetier-Server/modules/firmware/bin`

**Pull request closed without merging**
